import Header from "@/components/organisms/Header"
import "./globals.css"
import type { Metadata } from "next"
import HeaderApple from "@/components/organisms/HeaderApple"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        {/* <Header /> */}
        <HeaderApple />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  )
}
